USE `Slyvka_db_lab7_variant66`

DELIMITER //

CREATE TRIGGER drug_name_equal_to_ministry
BEFORE INSERT
ON Drug FOR EACH ROW
BEGIN
	IF LEFT(NEW.name, 1) != LEFT(NEW.ministry_code, 1) THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = "FIRST LETTER OF DRUG NAME MUST BE EQUAL TO FIRST LETTER OF MINISTRY CODE";
    END IF;
END//